name: Docker Build & Push

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_IMAGE_NAME: your-dockerhub-username/your-dockerhub-repo-name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME .
          docker push $DOCKER_IMAGE_NAME
